import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

ThemeData lightTheme = FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff6759ff),
    primaryContainer: Color(0xfff9f9f9),
    secondary: Color(0xff5d50e6),
    secondaryContainer: Color(0xffffffff),
    tertiary: Color(0xfff3944e),
    tertiaryContainer: Color(0xff95f0ff),
    appBarColor: Color(0xffffffff),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.highSurfaceLowScaffold,
  blendLevel: 4,
  appBarStyle: FlexAppBarStyle.custom,
  transparentStatusBar: true,
  appBarElevation: 2.0,
  tabBarStyle: FlexTabBarStyle.forBackground,
  subThemesData: const FlexSubThemesData(
    useFlutterDefaults: true,
    blendOnLevel: 15,
    blendOnColors: false,
    bottomSheetRadius: 4.0,
    textButtonRadius: 4.0,
    elevatedButtonRadius: 8.0,
    outlinedButtonRadius: 8.0,
    textButtonSchemeColor: SchemeColor.onSecondaryContainer,
    elevatedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonSchemeColor: SchemeColor.onSurfaceVariant,
    inputDecoratorRadius: 14.0,
    cardRadius: 4.0,
    appBarBackgroundSchemeColor: SchemeColor.onPrimary,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.inversePrimary,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.inversePrimary,
    bottomNavigationBarBackgroundSchemeColor: SchemeColor.primary,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
    navigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimary,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarUnselectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarIndicatorSchemeColor: SchemeColor.onSecondary,
    navigationBarBackgroundSchemeColor: SchemeColor.primary,
    navigationRailSelectedLabelSchemeColor: SchemeColor.onPrimary,
    navigationRailUnselectedLabelSchemeColor: SchemeColor.primaryContainer,
    navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationRailUnselectedIconSchemeColor: SchemeColor.primaryContainer,
    navigationRailIndicatorSchemeColor: SchemeColor.onPrimary,
    navigationRailIndicatorOpacity: 0.16,
    navigationRailBackgroundSchemeColor: SchemeColor.primary,
    navigationRailOpacity: 0.90,
    navigationRailLabelType: NavigationRailLabelType.none,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
// To use the playground font, add GoogleFonts package and uncomment
// fontFamily: GoogleFonts.notoSans().fontFamily,
);


