import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

ThemeData darkTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff6759ff),
    primaryContainer: Color(0xff00202f),
    secondary: Color(0xff18202e),
    secondaryContainer: Color(0xff870400),
    tertiary: Color(0xff0f1621),
    tertiaryContainer: Color(0xff030406),
    appBarColor: Color(0xff870400),
    error: Color(0xffcf6679),
  ),
  usedColors: 5,
  surfaceMode: FlexSurfaceMode.highScaffoldLevelSurface,
  blendLevel: 40,
  appBarStyle: FlexAppBarStyle.primary,
  tabBarStyle: FlexTabBarStyle.forBackground,
  swapColors: true,
  tooltipsMatchBackground: true,
  subThemesData: const FlexSubThemesData(
    useFlutterDefaults: true,
    blendOnLevel: 40,
    blendTextTheme: false,
    bottomSheetRadius: 4.0,
    textButtonRadius: 4.0,
    elevatedButtonRadius: 8.0,
    outlinedButtonRadius: 8.0,
    textButtonSchemeColor: SchemeColor.onSecondaryContainer,
    elevatedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonSchemeColor: SchemeColor.onSurfaceVariant,
    inputDecoratorSchemeColor: SchemeColor.secondary,
    inputDecoratorRadius: 14.0,
    cardRadius: 8.0,
    appBarBackgroundSchemeColor: SchemeColor.background,
    tabBarItemSchemeColor: SchemeColor.onPrimary,
    tabBarIndicatorSchemeColor: SchemeColor.primary,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.onSurfaceVariant,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.onSurfaceVariant,
    bottomNavigationBarBackgroundSchemeColor: SchemeColor.background,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
    navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
    navigationBarIndicatorSchemeColor: SchemeColor.onPrimary,
    navigationBarBackgroundSchemeColor: SchemeColor.background,
    navigationRailSelectedLabelSchemeColor: SchemeColor.onPrimary,
    navigationRailUnselectedLabelSchemeColor: SchemeColor.inverseSurface,
    navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationRailUnselectedIconSchemeColor: SchemeColor.inverseSurface,
    navigationRailIndicatorSchemeColor: SchemeColor.onPrimary,
    navigationRailIndicatorOpacity: 0.16,
    navigationRailBackgroundSchemeColor: SchemeColor.primary,
    navigationRailOpacity: 0.90,
    navigationRailLabelType: NavigationRailLabelType.none,
  ),
  useMaterial3ErrorColors: true,
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
);
